services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/ManGen?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - key=${key}
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ManGen
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: