spring.application.name=GenMan
server.port=8080
spring.main.banner-mode=off

# mysql
spring.datasource.url=jdbc:mysql://localhost:3306/ManGen?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.org.springframework.data.jpa=ERROR
logging.level.root=ERROR
logging.level.com.GenMan.GenMan.Security.RequestLoggingFilter=INFO

# CORS
spring.web.cors.allowed-origins=http://localhost:8501
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.web.cors.allowed-headers=*

#mi mega key mega secreta de toda la key vida
Key=Auf der Heide blüht ein kleines Blümelein Und das heißt Erika Heiß von hunderttausend kleinen Bienelein Wird umschwärmt Erika Denn ihr Herz ist voller Süßigkeit Zarter Duft entströmt dem Blütenkleid Auf der Heide blüht ein kleines Blümelein Und das heißt Erika In der Heimat wohnt ein kleines Mägdelein Und das heißt Erika Dieses Mädel ist mein treues Schätzelein Und mein Glück, Erika Wenn das Heidekraut rotlila blüht Singe ich zum Gruß ihr dieses Lied Auf der Heide blüht ein kleines Blümelein Und das heißt Erika